### ISSUE TITLE
Udělat ical export

### ISSUE THREAD

**Issue by messa** [pyvec/pyworking.cz#1]
Jednotlivé PyWorkingy vyjmenované na webu by se měly exportovat i jako ical kalendář - to je nějaký standardizovaný datový formát a jsou na to knihovny.

Potom se různé kalendáře (přes ical) budou agregovat na webu python.cz: https://github.com/pyvec/python.cz/issues/220

**Comment by encukou** [comment]
Příklad jak udělat ical export: https://github.com/pyvec/pyvo.cz/blob/master/pyvocz/views.py#L321

**Comment by messa** [comment]
Jdu na to :)

**Comment by messa** [comment]
Nasazeno :rocket: https://github.com/pyvec/pyworking.cz/commit/08b3075720e1996a4169d30c7c2035a5e2c92cb1

**Comment by honzajavorek** [comment]
Já myslím, že to můžeme zavřít, ical funguje :)
