### ISSUE TITLE
Dodat info o workshopu o testování

### ISSUE THREAD

**Issue by messa** [pyvec/pyworking.cz#12]
Který bude zřejmě ~17. února~ 24. března.

@hroncok, @zoellenka

**Comment by messa** [comment]
Souvisí s https://github.com/pyvec/pyworking-materials/issues/16 :yum:

**Comment by hroncok** [comment]
Dodám info o obsahu. Info o místě, a organizační info musí dodat někdo jiný.

**Comment by zoellenka** [comment]
pracuju na tom :)
