### ISSUE TITLE
Přidat logo Akamai

### ISSUE THREAD

**Issue by messa** [pyvec/pyworking.cz#13]
Jakožto podporovatele Pyworking Sessions.

**Comment by tystar86** [comment]
![27583905_2062428300439174_68141246_n](https://user-images.githubusercontent.com/24453683/35613392-36975774-066c-11e8-9f4a-edff85569a32.png)

**Comment by messa** [comment]
@tystar86 super, díky, přidám ho rovnou do nového designu (#8)

**Comment by IvaFingerova** [comment]
Přidala bych to jako další sekci pod Příští setkání 
Místo setkání:
Kanceláře Akamai
Karla Engliše 4, Praha 5
5. patro
Logo bych pak zarovnala vpravo

**Comment by messa** [comment]
@IvaFingerova tak jsem to tam dal a posunul logo - co na to říkáš? Je to na www.pyworking.cz

![image](https://user-images.githubusercontent.com/115487/38805910-ddf01f92-4177-11e8-96a1-0c39d0373ca0.png)

**Comment by messa** [comment]
Logo už tam delší dobu je, žádné připomínky nebyly, uzavírám :)
