### ISSUE TITLE
Opravit popis na meetup.com

### ISSUE THREAD

**Issue by messa** [pyvec/pyworking.cz#20]
Na stránce https://www.meetup.com/pyworking/ je ještě starý popis z dob Pyladies:

> PyLadies is an international mentorship group with a focus on helping more women become active participants and leaders in the Python open-source community. Our mission is to ...

Lidi to čtou a jsou pak zmatení.

Šlo by s tím prosím něco udělat? @IvaFingerova nebo někdo jiný :)

**Comment by IvaFingerova** [comment]
Hotofoooo
