### ISSUE TITLE
Aktualizace příjemců info@pyworking.cz

### ISSUE THREAD

**Issue by messa** [pyvec/pyworking.cz#22]
Takový trochu followup k #2 :) Potřebujeme nastavit, aby e-maily, které přijdou na info@pyworking.cz, chodily těmto (a jen těmto) lidem:

petr.messner@gmail.com
fingerova.iva@gmail.com
eliska.doktorova@gmail.com
radka.plankova@gmail.com

Kdo to může nastavit? :) @honzajavorek @kvbik @martinbilek

**Comment by aleszoulek** [comment]
Hotovo.
