### ISSUE TITLE
Přidat workshop API 

### ISSUE THREAD

**Issue by radusaaa** [pyvec/pyworking.cz#29]
viz FB 
https://www.facebook.com/events/462772517546969/

díky!

**Comment by encukou** [comment]
Řešíte tohle nějak v Praze? Mám to řešit já?

**Comment by messa** [comment]
Zatím jsem na to neměl čas. Podívám se na to za chvíli.

**Comment by messa** [comment]
Zde: https://pyworking.cz/workshops/20181110_Webova_API
