### ISSUE TITLE
Čtrnáctidenní Sessions?

### ISSUE THREAD

**Issue by hroncok** [pyvec/pyworking.cz#30]
Z hlavní stránky:

> Pyworkingy jsou setkání Pythonistů začátečníků, kteří se chtějí učit nové věci nebo se zdokonalovat v základech. Pořádáme tématické celodenní Workshopy s připravenou výukou, ale také **čtrnáctidenní Sessions** pro samostudium za dozoru koučů.

To asi nepořádáme, ne?

**Comment by messa** [comment]
Rovnou tam asi zkusím zvýraznit workshopy a sessions

**Comment by messa** [comment]
Before:

![image](https://user-images.githubusercontent.com/115487/48143141-77638d80-e2ae-11e8-8078-75aa7f373d5e.png)

After:

![image](https://user-images.githubusercontent.com/115487/48143173-86e2d680-e2ae-11e8-8416-918e4d0bb4a4.png)

**Comment by messa** [comment]
Je to už i nasazené.

@IvaFingerova approves? :)
