### ISSUE TITLE
Zdokumentovat nebo automatizovat nasazení

### ISSUE THREAD

**Issue by encukou** [pyvec/pyworking.cz#42]
@messa neškáluje. Co můžu udělat pro to, aby se pyworking.cz mohl nasadit když má zrovna moc práce?

**Comment by encukou** [comment]
@messa řekl na Slacku:

> Aktuálně to běží jako Docker kontejner na mém virtuálním serveru, na kterém běží různé webovky. Já se tam vždy přes SSH přihlásím a pustím deploy skript. Donedávna to bylo potřeba jen párkrát ročně :slightly_smiling_face: Toto by se dalo zautomatizovat přes CI.
> Ale vzhledem k tomu, web Pyworkingu nemusí být dynamický, tak by bylo fajn to předělat na statický export plus upload někam (na S3 nebo Github pages).

Takže aby se to nastavilo stejně jako pyladies.cz, pyvec.org nebo books.pyvo.cz:
1. [ ] Nastavit [Elsu](https://github.com/pyvec/elsa/) a Travis CI
2. [ ] Nastavit práva uživateli @pyvecpusher, pak říct Mirovi ať vygeneruje a pošle přihlašovací token
3. [ ] Nastavit DNS (žádost do kanálu `#domeny` na Slacku; může změnit např @encukou)

**Comment by messa** [comment]
DNS: pyworking.cz je pod Pyvcem, nsset IGNUM, přímý přístup k tomu nemám, o změny se dá myslím žádat na Pyvec Slacku.
