### ISSUE TITLE
Distribuce pythonních programů není na pyworking.cz

### ISSUE THREAD

**Issue by hroncok** [pyvec/pyworking.cz#6]
Je to jen na Facebooku https://www.facebook.com/events/1953829801535289/

**Comment by messa** [comment]
Dám to tam

**Comment by messa** [comment]
Je to na [webu](https://pyworking.cz/) ([commit](https://github.com/pyvec/pyworking.cz/commit/6d904a98927863651afe499e97fa26ebba879bf0))

Je to takhle ok?

**Comment by hroncok** [comment]
Díky.
