### ISSUE TITLE
Přidat 14 denní PyWorkingy na web

### ISSUE THREAD

**Issue by IvaFingerova** [pyvec/pyworking.cz#8]
Pojďme přidat na web pyworking.cz sekci o 14 denních PyWorkinzích.
Iva a Štěpánka a Petr si zabrainstormují :)

**Comment by messa** [comment]
Vývoj zatím probíhá ve větvi https://github.com/messa/pyworking.cz/tree/redesign_201801

Aktuální podoba: https://pyworkingcz-jawfqlhusb.now.sh/

**Comment by messa** [comment]
Aktuální podoba: https://pyworkingcz-zyxllbjfpy.now.sh/

Přemýšlím o tom, že by se popis workshopů načítal rovnou z readme.md v [pyworking-materials](https://github.com/pyvec/pyworking-materials), tj. že v souborech typu [data/events/20180120_Brno_Django.yaml](https://github.com/pyvec/pyworking.cz/blob/eaa2027ac45ea747f52e964e7a465ee593e3bf98/data/events/20180120_Brno_Django.yaml) by nebyla hodnota `description` (popř. by byla volitelná a asi zřídka využívaná).

**Comment by zoellenka** [comment]
super, jsem pro

**Comment by encukou** [comment]
Prosím aby byla volitelná. Rád měl možnost dělat PyWorkingy podle jiných materiálů – zrovna ten [první brněnský](https://github.com/pyvec/pyworking.cz/blob/eaa2027ac45ea747f52e964e7a465ee593e3bf98/data/events/20180120_Brno_Django.yaml) jel podle DjangoGirls a v pyworking-materials není.
